title: Monocular Depth Estimation Challenge
description: MDEC @ WACV 2023

theme: jekyll-theme-cayman

markdown: kramdown

# Remove `View on GitHub` & Download buttons
show_downloads: false
github:
  is_project_page: false

plugins:
  - jemoji